

Auto-repair-on-start: true

Send-Cooldown-Message:
  Enabled: true
  # placeholders:
  # {Time}: gets the remaining time.
  # {ItemName}: gets the name of the clicked item.
  # {ProjName}: gets the used projectile's name.
  # use & or § for colors (full list here: https://htmlcolorcodes.com/minecraft-color-codes/).
  Message: "&cYou have to wait {Time} more seconds before you can use that again!"

Permissions:
  #if this is enabled, every projectile will need a permission to use it
  Enabled: false
  Permission: "Projectile.{ProjName}"
  Message: "&cYou don't have permission to use that!"


#mana system for this plugin. displays on the action bar.
# {ManaLeft} - the player's mana
# {MaxMana} - the player's max mana
Mana:
  Enabled: true
  ActionBar: true
  Display: "&b             ✎ {ManaLeft}/{MaxMana}             "
  MaxMana: 100.0
  ManaRegen: 5.0  #the amount of mana regen per second
  NotEnoughManaMessage: "&cYou don't have enough mana to use this!"

#Enjoy the plugin? feel free to leave a 5 stars review on spigot <3
#https://www.spigotmc.org/resources/arcaneprojectiles-simple-gui-shoot-any-entity.103005/reviews
# DM @just a cat#7594 on discord for support!